apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hda3vl30e-python
  janus-idp.io/tekton: hda3vl30e-python
  backstage.io/kubernetes-id: hda3vl30e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hda3vl30e-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
