apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hda3vl30e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hda3vl30e-python 
  name: hda3vl30e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hda3vl30e-python 
